version: "3.8"
services:
  api-service:
    container_name: api-service
    image: nginx:alpine
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-service.rule=Host(`api.localhost`)"
      - "traefik.http.routers.api-service.entrypoints=web"
      - "traefik.http.services.api-service.loadbalancer.server.port=80"
      - "traefik.http.routers.api-service.middlewares=api-stripprefix"
      - "traefik.http.middlewares.api-stripprefix.stripprefix.prefixes=/api"
    volumes:
      - api-content:/usr/share/nginx/html
    restart: unless-stopped

volumes:
  api-content:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/experimentalist/Scripts/docker-ops-manager/examples/api 