version: "3.8"

services:
  nginx:
    container_name: nginx-app
    image: nginx:alpine
    ports:
      - "8081:80"
    environment:
      - NGINX_HOST=localhost
    volumes:
      - /Users/experimentalist/Scripts/docker-ops-manager/examples/nginx/html:/usr/share/nginx/html
      - /Users/experimentalist/Scripts/docker-ops-manager/examples/nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    driver: bridge

volumes:
  nginx_data:
    driver: local 