version: "3.8"
services:
  web-app:
    container_name: web-app
    image: nginx:alpine
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web-app.rule=Host(`web.localhost`)"
      - "traefik.http.routers.web-app.entrypoints=web"
      - "traefik.http.services.web-app.loadbalancer.server.port=80"
    volumes:
      - html-content:/usr/share/nginx/html
    restart: unless-stopped

volumes:
  html-content:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/experimentalist/Scripts/docker-ops-manager/examples/html 